version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo "Running build"
      - echo "Chaljaa"
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://asna-project-bucket --delete
