version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo "Running build"
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ http://asna-project-bucket.s3-website-us-east-1.amazonaws.com
artifacts:
  files:
    - '**/*'
  base-directory: build
